version: "v1"
app:
  port: 8080
  debug: true
awarent:
  serviceName: ddv
  nacos:
    ip: 192.168.1.71
    port: 8848
  config:
    #uniq id for config
    dataId: ddv-config
    # group example  test/dev/prod
    group: test  