version: "v1"
app:
  port: 8080
  debug: true
awarent:
  serviceName: ddv
  #group test/dev/prod
  group: test
  nacos:
    ip: 192.168.1.71
    port: 8848
  config:
    #config id
    dataId: ddv-config